#!/bin/bash

if [ "$1" = "--init" ]; then
    git clone https://github.com/DSW50610/lab4.git ./
    export PATH=$PATH:$(pwd)
fi

git add plik1
git commit -m
git push
git checkout main
git merge taskBranch
